Release version 0.1.16

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -18,11 +18,21 @@ jobs:
       with:
         python-version: '3.12'
 
+    - name: Install build tools
+      run: sudo apt-get update && sudo apt-get install -y build-essential
+
     - name: Create virtual environment
       run: python3 -m venv ${{ runner.temp }}/venv
 
     - name: Activate virtual environment
       run: source ${{ runner.temp }}/venv/bin/activate
+
+    - name: Check for requirements.txt
+      run: |
+        if [ ! -f requirements.txt ]; then
+          echo "requirements.txt not found"
+          exit 1
+        fi
 
     - name: Install dependencies
       run: pip install -r requirements.txt
